# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b731bd92bb6f9d96b97aee44ab05c41710969834c55b714b622b7f9ac605b7b29540da76a1f86c0541bf6dba772949414bbbf16db9ec112711bc3d54c8d60d9c

test:
  secret_key_base: 13cdeb35bb1f53348a511cf37c539ef8521877eda106ac2087e5e07b5f39c0fb6d950c4c542ea2da99e818ecbd40795deabab37cd9675493e24725f4c0986433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
